name: CI/CD for Databricks

on:
  push:
    branches:
      - main
      - Feature1
  pull_request:
    branches:
      - main
      - Feature1

jobs:
  Unit and Integrity tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                    
      - name: Run unit tests
        run: pytest --nbval tests/unit

      - name: Run integration tests
        run: pytest --nbval tests/integration

  Deployment to Production:
    if: github.ref == 'refs/heads/main'
    needs: Unit and Integrity tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Deploy to Databricks
        run: |
          # Example: Deploy all files in /notebooks folder to workspace /Production
          for file in notebooks/*; do
            databricks workspace import "$file" "/Production/$(basename "$file")" --format JUPYTER --overwrite
          done