name: CI for Databricks

on:
  push:
    branches:
      - main
      - Feature1
  pull_request:
    branches:
      - main
      - Feature1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                    
      - name: Run unit tests
        run: pytest --nbval tests/unit

      - name: Run integration tests
        run: pytest --nbval tests/integration